version: "2"

networks:
  giteadrone:
    external: false

services:
  forwardproxy:
    image: forwardproxy:local
    restart: always
    networks:
      - giteadrone
    ports:
      - "7777:8888"

  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=502
      - USER_GID=20
    restart: always
    networks:
      - giteadrone
    volumes:
      - ./gitea/data:/data
      - ./etc/timezone:/etc/timezone:ro
      - ./etc/localtime:/etc/localtime:ro
    ports:
      - "3333:3000"
      - "4444:22"
