version: "2"

networks:
  giteadrone:
    external: false

services:
  forwardproxy:
    image: forwardproxy:latest
    restart: always
    networks:
      - giteadrone
    ports:
      - "7777:8888"

  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=502
      - USER_GID=20
    restart: always
    networks:
      - giteadrone
    volumes:
      - ./gitea/data:/data
      - ./etc/timezone:/etc/timezone:ro
      - ./etc/localtime:/etc/localtime:ro
    ports:
      - "3333:3000"
      - "4444:22"

  drone:
    image: drone/drone:1
    environment:
      - DRONE_SERVER_HOST=drone
      - DRONE_SERVER_PROTO=http
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GITEA_SERVER=http://gitea:3000
      - DRONE_GITEA_CLIENT_ID=8af4ed1b-6591-4c1e-9646-a92e4091f5d2
      - DRONE_GITEA_CLIENT_SECRET=cT4ylyBYkbOZRnh03-IT8cX2IwT9FgQGdAVgn08QFbE=
      - DRONE_RPC_SECRET=Y29tbWFuZGVydmltZXMK
    restart: always
    networks:
      - giteadrone
    volumes:
      - ./drone/data:/data
    ports:
      - "5555:80"

  drone-runner:
    image: drone/drone-runner-docker:1
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=drone
      - DRONE_RPC_SECRET=Y29tbWFuZGVydmltZXMK
      - DRONE_RUNNER_CAPACITY=4
      - DRONE_RUNNER_NAME=r2d2
    networks:
      - giteadrone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:3000

