version: "2"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    environment:
      - USER_UID=502
      - USER_GID=20
    restart: always
    networks:
      - gitea
    volumes:
      - ./data:/data
      - ./etc/timezone:/etc/timezone:ro
      - ./etc/localtime:/etc/localtime:ro
    ports:
      - "3333:3000"
      - "4444:22"
